-- Run these ONE AT A TIME in Supabase SQL Editor.
-- After each one, check if it says "Success".
-- If you get an error, tell me which line.

ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS semester character varying;
ALTER TABLE public.gallery ADD COLUMN IF NOT EXISTS caption character varying;
CREATE TABLE IF NOT EXISTS public.enrollment_inquiries (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_name character varying NOT NULL,
    email character varying NOT NULL,
    phone character varying,
    child_name character varying,
    class_applying character varying,
    message text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT enrollment_inquiries_pkey PRIMARY KEY (id)
);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS profile_picture text;
