-- migrate_calendar_module.sql
-- Creates the academic calendar events table and seeds the 3rd term 2025/2026 events.
-- Run this in Supabase SQL Editor.

-- ============================================================
-- TABLE: academic_calendar_events
-- Stores termly calendar events for display on public pages,
-- staff portal, and attendance period validation.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.academic_calendar_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT NULL,
    event_date DATE NOT NULL,
    end_date DATE,                              -- NULL for single-day events
    event_type VARCHAR DEFAULT 'event',          -- 'event', 'holiday', 'exam', 'training', 'break'
    description TEXT,
    color VARCHAR DEFAULT '#3498db',             -- hex color for display
    academic_year VARCHAR DEFAULT '2025/2026',
    term INTEGER DEFAULT 3,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT academic_calendar_events_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_calendar_events_date ON public.academic_calendar_events(event_date);
CREATE INDEX IF NOT EXISTS idx_calendar_events_year_term ON public.academic_calendar_events(academic_year, term);

-- ============================================================
-- SEED: 3rd Term 2025/2026 Events (from Chariot Educational Complex planner)
-- ============================================================
INSERT INTO academic_calendar_events (title, event_date, end_date, event_type, color, sort_order) VALUES
    ('Staff & Learners Reopening / Settling In',   '2026-05-04', '2026-05-05', 'event',    '#27ae60', 1),
    ('General Meeting',                             '2026-05-22', NULL,        'event',    '#8e44ad', 2),
    ('A.U Day',                                     '2026-05-25', NULL,        'event',    '#f39c12', 3),
    ('Republic Day (Holiday)',                      '2026-05-27', NULL,        'holiday',  '#e74c3c', 4),
    ('Games',                                       '2026-05-29', NULL,        'event',    '#2ecc71', 5),
    ('Spelling Bee',                                '2026-06-05', NULL,        'event',    '#3498db', 6),
    ('Moving Library Competition',                  '2026-06-12', NULL,        'event',    '#9b59b6', 7),
    ('Mid Term Exams',                              '2026-06-16', '2026-06-18', 'exam',     '#e67e22', 8),
    ('Staff Training',                              '2026-06-19', NULL,        'training', '#1abc9c', 9),
    ('School Resumes',                              '2026-06-22', NULL,        'event',    '#27ae60', 10),
    ('Submission of Test Items',                    '2026-06-26', NULL,        'event',    '#f1c40f', 11),
    ('Rep Your Jersey',                             '2026-06-26', NULL,        'event',    '#e74c3c', 12),
    ('Republic Day (Holiday)',                      '2026-07-01', NULL,        'holiday',  '#e74c3c', 13),
    ('Staff Training',                              '2026-07-03', NULL,        'training', '#1abc9c', 14),
    ('Games',                                       '2026-07-10', NULL,        'event',    '#2ecc71', 15),
    ('Traditional Day Dressing',                    '2026-07-17', NULL,        'event',    '#e67e22', 16),
    ('End of Academic Year Exams',                  '2026-07-24', '2026-07-28', 'exam',     '#c0392b', 17),
    ('Career Day Dressing',                         '2026-07-29', NULL,        'event',    '#2980b9', 18),
    ('Vacation',                                    '2026-07-30', '2026-07-31', 'break',    '#95a5a6', 19)
ON CONFLICT DO NOTHING;

-- ============================================================
-- Set default academic calendar dates in system_settings
-- if not already set
-- ============================================================
INSERT INTO system_settings (setting_key, setting_value)
SELECT 'academic_calendar_start', '2026-05-04'
WHERE NOT EXISTS (SELECT 1 FROM system_settings WHERE setting_key = 'academic_calendar_start');

INSERT INTO system_settings (setting_key, setting_value)
SELECT 'academic_calendar_end', '2026-07-31'
WHERE NOT EXISTS (SELECT 1 FROM system_settings WHERE setting_key = 'academic_calendar_end');

INSERT INTO system_settings (setting_key, setting_value)
SELECT 'calendar_term_label', '3rd Term — 2025/2026 Academic Year'
WHERE NOT EXISTS (SELECT 1 FROM system_settings WHERE setting_key = 'calendar_term_label');

-- ============================================================
-- Show results
-- ============================================================
SELECT COUNT(*) AS calendar_events_seeded FROM academic_calendar_events;
SELECT setting_key, setting_value FROM system_settings WHERE setting_key LIKE 'academic_calendar%' OR setting_key = 'calendar_term_label';
