-- ============================================================
-- INFOTESS SDMS — PRODUCTION POSTGRESQL SCHEMA
-- ============================================================
-- This is the authoritative schema for the running PostgreSQL
-- database (Infotess-host deployment, integer PKs, no RLS).
--
-- ✅ Runnable in order — no FK ordering issues
-- ✅ Uses GENERATED BY DEFAULT AS IDENTITY (PostgreSQL 10+)
-- ✅ Includes ALL FK constraints present in the running DB
-- ============================================================

-- Required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";  -- for fee_structures.uuid

-- ============================================================
-- LEVEL 0: Standalone tables (no FK dependencies)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.activities (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    description text NOT NULL,
    activity_date timestamp with time zone NOT NULL,
    image_url text,
    registration_link character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alumni (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name character varying NOT NULL,
    graduation_year character varying NOT NULL,
    position character varying,
    company character varying,
    image_url text,
    testimonial text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT alumni_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.classes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    level_group character varying NOT NULL DEFAULT 'basic'::character varying,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT classes_pkey PRIMARY KEY (id),
    CONSTRAINT classes_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.contact_submissions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    email character varying NOT NULL,
    subject character varying,
    message text NOT NULL,
    response text,
    responded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT contact_submissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gallery (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying,
    caption character varying,
    image_url text NOT NULL,
    category character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT gallery_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    description text,
    event_date timestamp with time zone NOT NULL,
    location character varying,
    source_url text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.news (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    content text,
    source_url text,
    image_url text,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT news_pkey PRIMARY KEY (id),
    CONSTRAINT news_source_url_key UNIQUE (source_url)
);

CREATE TABLE IF NOT EXISTS public.resources (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    description text,
    file_url text NOT NULL,
    category character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT resources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_resources (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    description text,
    file_url text NOT NULL,
    resource_type character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT student_resources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grade_boundaries (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    min_score integer NOT NULL,
    max_score integer NOT NULL,
    grade integer,
    remark character varying,
    CONSTRAINT grade_boundaries_pkey PRIMARY KEY (id),
    CONSTRAINT grade_boundaries_score_range_key UNIQUE (min_score, max_score)
);

CREATE TABLE IF NOT EXISTS public.projects (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    description text,
    image_url text,
    project_date date,
    status character varying DEFAULT 'completed'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT projects_status_check CHECK (status::text = ANY (ARRAY['completed'::character varying, 'ongoing'::character varying, 'planned'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS public.sessions (
    id character varying NOT NULL,
    data text NOT NULL DEFAULT ''::text,
    last_accessed timestamp with time zone DEFAULT now(),
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_settings (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    setting_key character varying NOT NULL,
    setting_value text,
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT system_settings_pkey PRIMARY KEY (id),
    CONSTRAINT system_settings_setting_key_key UNIQUE (setting_key)
);

CREATE TABLE IF NOT EXISTS public.terms (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    academic_year character varying NOT NULL,
    start_date date,
    end_date date,
    is_active boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT terms_pkey PRIMARY KEY (id),
    CONSTRAINT terms_name_academic_year_key UNIQUE (name, academic_year)
);

-- ============================================================
-- LEVEL 1: Depend on LEVEL 0 tables (users, classes, etc.)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying NOT NULL,
    password character varying NOT NULL,
    role character varying DEFAULT 'student'::character varying,
    status character varying DEFAULT 'active'::character varying,
    is_password_reset boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    profile_picture text,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.staff (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer,
    staff_id character varying,
    full_name character varying NOT NULL,
    position character varying NOT NULL,
    department character varying,
    qualification character varying,
    phone character varying,
    email character varying,
    date_of_birth date,
    gender character varying,
    address text,
    hire_date date,
    status character varying NOT NULL DEFAULT 'active'::character varying,
    bank_name character varying,
    account_number character varying,
    created_at timestamp with time zone DEFAULT now(),
    profile_picture text,
    cv_path text,
    documents text,
    CONSTRAINT staff_pkey PRIMARY KEY (id),
    CONSTRAINT staff_staff_id_key UNIQUE (staff_id),
    CONSTRAINT staff_email_key UNIQUE (email),
    CONSTRAINT staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.students (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer,
    full_name character varying NOT NULL,
    stream character varying,
    phone_number character varying,
    created_at timestamp with time zone DEFAULT now(),
    class_name character varying,
    guardian_name character varying,
    guardian_phone character varying,
    gender character varying,
    date_of_birth date,
    address text,
    status character varying DEFAULT 'active'::character varying,
    enrollment_type character varying DEFAULT 'admin'::character varying,
    enrollment_id character varying,
    payment_status character varying DEFAULT 'unpaid'::character varying,
    guardian_email character varying,
    guardian_relationship character varying,
    guardian_phone_primary character varying,
    guardian_phone_emergency character varying,
    guardian_occupation character varying,
    guardian_address text,
    place_of_birth character varying,
    nationality character varying DEFAULT 'Ghanaian'::character varying,
    hometown character varying,
    profile_picture text,
    health_insurance_id character varying,
    blood_group character varying,
    genotype character varying,
    medical_conditions text,
    allergies text,
    special_needs text,
    previous_school character varying,
    previous_class character varying,
    admission_date date DEFAULT CURRENT_DATE,
    academic_year character varying,
    admission_term character varying DEFAULT '1',
    admission_number character varying,
    CONSTRAINT students_pkey PRIMARY KEY (id),
    CONSTRAINT students_enrollment_id_key UNIQUE (enrollment_id),
    CONSTRAINT students_admission_number_key UNIQUE (admission_number),
    CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.enrollment_inquiries (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_name character varying NOT NULL,
    email character varying NOT NULL,
    phone character varying,
    child_name character varying,
    class_applying character varying,
    message text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT enrollment_inquiries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.executives (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer,
    position character varying NOT NULL,
    full_name character varying NOT NULL,
    phone character varying,
    email character varying,
    academic_year character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT executives_pkey PRIMARY KEY (id),
    CONSTRAINT executives_user_id_fkey FOREIGN KEY (user_id) REFERENCES 
public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.fee_structures (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    school_id uuid,
    title character varying NOT NULL,
    amount numeric NOT NULL,
    academic_year character varying,
    term character varying,
    is_mandatory boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    fee_type character varying NOT NULL DEFAULT 'school_fees'::character varying,
    class_id integer,
    CONSTRAINT fee_structures_pkey PRIMARY KEY (id),
    CONSTRAINT fee_structures_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.subjects (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    code character varying,
    class_id integer,
    teacher_id integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT subjects_pkey PRIMARY KEY (id),
    CONSTRAINT subjects_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE,
    CONSTRAINT subjects_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.messages (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sender_id integer,
    receiver_id integer,
    title character varying NOT NULL,
    content text NOT NULL,
    is_broadcast boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    read_at timestamp with time zone,
    CONSTRAINT messages_pkey PRIMARY KEY (id),
    CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer,
    title character varying NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- Note: audit_logs table was in legacy MySQL but is NOT created in the
-- current Basic School migration (migrate-all.sql). Do not add it back
-- unless the PHP audit logging feature is re-implemented first.

-- ============================================================
-- LEVEL 2: Depend on LEVEL 1 tables
-- ============================================================

CREATE TABLE IF NOT EXISTS public.deductions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    staff_id integer,
    deduction_type character varying NOT NULL,
    amount numeric NOT NULL,
    description text,
    is_recurring boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT deductions_pkey PRIMARY KEY (id),
    CONSTRAINT deductions_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.salary_structures (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    staff_id integer,
    basic_salary numeric NOT NULL DEFAULT 0,
    housing_allowance numeric DEFAULT 0,
    transport_allowance numeric DEFAULT 0,
    other_allowances numeric DEFAULT 0,
    ssnit_rate numeric DEFAULT 13.50,
    tax_rate numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT salary_structures_pkey PRIMARY KEY (id),
    CONSTRAINT salary_structures_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.payroll (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    staff_id integer,
    month integer NOT NULL,
    year integer NOT NULL,
    basic_salary numeric DEFAULT 0,
    total_allowances numeric DEFAULT 0,
    gross_pay numeric DEFAULT 0,
    ssnit_deduction numeric DEFAULT 0,
    tax_deduction numeric DEFAULT 0,
    other_deductions numeric DEFAULT 0,
    total_deductions numeric DEFAULT 0,
    net_pay numeric DEFAULT 0,
    status character varying DEFAULT 'pending'::character varying,
    pay_date date,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT payroll_pkey PRIMARY KEY (id),
    CONSTRAINT payroll_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.staff_attendance (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    staff_id integer,
    attendance_date date NOT NULL,
    check_in timestamp with time zone,
    check_out timestamp with time zone,
    status character varying NOT NULL DEFAULT 'present'::character varying,
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT staff_attendance_pkey PRIMARY KEY (id),
    CONSTRAINT staff_attendance_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id) ON DELETE CASCADE,
    CONSTRAINT staff_attendance_staff_date_key UNIQUE (staff_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS public.staff_invites (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    staff_id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying NOT NULL,
    status character varying NOT NULL DEFAULT 'pending'::character varying,
    invited_by integer,
    invited_at timestamp with time zone DEFAULT now(),
    accepted_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    email_sent boolean DEFAULT false,
    sms_sent boolean DEFAULT false,
    CONSTRAINT staff_invites_pkey PRIMARY KEY (id),
    CONSTRAINT staff_invites_token_key UNIQUE (token),
    CONSTRAINT staff_invites_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id) ON DELETE CASCADE,
    CONSTRAINT staff_invites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT staff_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.attendance_summary (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    month integer NOT NULL,
    year integer NOT NULL,
    total_school_days integer DEFAULT 0,
    present integer DEFAULT 0,
    absent integer DEFAULT 0,
    late integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT attendance_summary_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_summary_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.exam_scores (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    subject_id integer,
    term_id integer,
    exam_score numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT exam_scores_pkey PRIMARY KEY (id),
    CONSTRAINT exam_scores_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE,
    CONSTRAINT exam_scores_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE,
    CONSTRAINT exam_scores_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.terms(id) ON DELETE CASCADE,
    CONSTRAINT exam_scores_student_subject_term_key UNIQUE (student_id, subject_id, term_id)
);

CREATE TABLE IF NOT EXISTS public.sba_scores (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    subject_id integer,
    term_id integer,
    class_test numeric DEFAULT 0,
    mid_term numeric DEFAULT 0,
    end_term numeric DEFAULT 0,
    project numeric DEFAULT 0,
    attitude character varying,
    interest character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT sba_scores_pkey PRIMARY KEY (id),
    CONSTRAINT sba_scores_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE,
    CONSTRAINT sba_scores_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE,
    CONSTRAINT sba_scores_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.terms(id) ON DELETE CASCADE,
    CONSTRAINT sba_scores_student_subject_term_key UNIQUE (student_id, subject_id, term_id)
);



CREATE TABLE IF NOT EXISTS public.student_attendance (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    class_id integer,
    attendance_date date NOT NULL,
    status character varying NOT NULL DEFAULT 'present'::character varying,
    reason text,
    recorded_by integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT student_attendance_pkey PRIMARY KEY (id),
    CONSTRAINT student_attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE,
    CONSTRAINT student_attendance_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE,
    CONSTRAINT student_attendance_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT student_attendance_student_date_key UNIQUE (student_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS public.parent_students (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_user_id integer NOT NULL,
    student_id integer NOT NULL,
    relationship character varying,
    is_primary boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT parent_students_pkey PRIMARY KEY (id),
    CONSTRAINT parent_students_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT parent_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.message_reads (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    message_id integer,
    user_id integer,
    read_at timestamp with time zone DEFAULT now(),
    CONSTRAINT message_reads_pkey PRIMARY KEY (id),
    CONSTRAINT message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE,
    CONSTRAINT message_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT message_reads_message_user_key UNIQUE (message_id, user_id)
);

-- ============================================================
-- LEVEL 3: Depend on LEVEL 2 tables
-- ============================================================

CREATE TABLE IF NOT EXISTS public.pay_slips (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    payroll_id integer,
    pdf_path text,
    generated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT pay_slips_pkey PRIMARY KEY (id),
    CONSTRAINT pay_slips_payroll_id_fkey FOREIGN KEY (payroll_id) REFERENCES public.payroll(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.payments (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_id integer,
    amount numeric NOT NULL,
    academic_year character varying,
    term character varying,
    semester character varying,
    payment_method character varying,
    payment_date date DEFAULT CURRENT_DATE,
    receipt_number character varying NOT NULL,
    recorded_by integer,
    created_at timestamp with time zone DEFAULT now(),
    status character varying DEFAULT 'completed'::character varying,
    enrollment_id character varying,
    fee_type character varying,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT payments_receipt_number_key UNIQUE (receipt_number),
    CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE,
    CONSTRAINT payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.receipts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    payment_id integer NOT NULL,
    receipt_file_path text,
    verification_hash character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT receipts_pkey PRIMARY KEY (id),
    CONSTRAINT receipts_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.report_cards (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    term_id integer,
    class_position integer,
    total_students integer,
    class_teacher_remarks text,
    class_teacher_name character varying,
    headmaster_remarks text,
    headmaster_name character varying,
    next_term_begins date,
    pdf_path text,
    generated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT report_cards_pkey PRIMARY KEY (id),
    CONSTRAINT report_cards_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE,
    CONSTRAINT report_cards_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.terms(id) ON DELETE CASCADE,
    CONSTRAINT report_cards_student_term_key UNIQUE (student_id, term_id)
);

-- ============================================================
-- INDEXES on FK columns (commonly queried)
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_staff_user_id ON public.staff(user_id);
CREATE INDEX IF NOT EXISTS idx_students_user_id ON public.students(user_id);
CREATE INDEX IF NOT EXISTS idx_subjects_class_id ON public.subjects(class_id);
CREATE INDEX IF NOT EXISTS idx_subjects_teacher_id ON public.subjects(teacher_id);
CREATE INDEX IF NOT EXISTS idx_payments_student_id ON public.payments(student_id);
CREATE INDEX IF NOT EXISTS idx_payments_recorded_by ON public.payments(recorded_by);
CREATE INDEX IF NOT EXISTS idx_payroll_staff_id ON public.payroll(staff_id);
CREATE INDEX IF NOT EXISTS idx_salary_structures_staff_id ON public.salary_structures(staff_id);
CREATE INDEX IF NOT EXISTS idx_deductions_staff_id ON public.deductions(staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_staff_id ON public.staff_attendance(staff_id);
CREATE INDEX IF NOT EXISTS idx_student_attendance_student_id ON public.student_attendance(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_summary_student_id ON public.attendance_summary(student_id);
CREATE INDEX IF NOT EXISTS idx_exam_scores_student_id ON public.exam_scores(student_id);
CREATE INDEX IF NOT EXISTS idx_sba_scores_student_id ON public.sba_scores(student_id);
CREATE INDEX IF NOT EXISTS idx_parent_students_parent_user_id ON public.parent_students(parent_user_id);
CREATE INDEX IF NOT EXISTS idx_parent_students_student_id ON public.parent_students(student_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver_id ON public.messages(receiver_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);

CREATE INDEX IF NOT EXISTS idx_executives_user_id ON public.executives(user_id);
CREATE INDEX IF NOT EXISTS idx_report_cards_student_id ON public.report_cards(student_id);
CREATE INDEX IF NOT EXISTS idx_fee_structures_class_id ON public.fee_structures(class_id);

-- Indexes for missing tables added in schema fix
CREATE INDEX IF NOT EXISTS idx_receipts_payment_id ON public.receipts(payment_id);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON public.events(event_date);
